"""ContributingMdLoom — installs `CONTRIBUTING.md` if absent.

Sakichi vision 96: maintainers are edge developers, not a privileged class
above contributors. A missing CONTRIBUTING.md forces every new contributor
to discover the maintainer's norms by trial-and-error — through PR review
back-and-forth, through closed PRs that violated unstated conventions,
through Slack/Discord questions the maintainer answers individually each
time. The CONTRIBUTING.md is the loom that catches this: a one-time write
of the norms, available before the first contribution.

Failure mode prevented (V96): the maintainer absorbs onboarding cost
contributor-by-contributor instead of paying it once into a discoverable
file. Without this halt, the maintainer is the per-contributor
documentation. With it, the file is.

Per Komada-voice override 2026-04-26 of the why-first synthesis verdict:
this loom ships as planned in the SPA-AI 3-week launch plan W2-3.
Override file: `outputs/governance_transformation/komada_override_why_first_w2_3_2026_04_26.md`.
"""
from __future__ import annotations

from pathlib import Path

from .base import LoomFinding, LoomPatch

_DEFAULT_CONTRIBUTING = """\
# Contributing

Thank you for considering a contribution. This document is the maintainer's
attempt to make the first contribution as cheap as possible — for both of us.
Per the loom that installed it: maintainers are edge developers too, and
their time should be spent on judgment work, not on per-contributor
onboarding answers.

## What contributions are welcome

- **Bug fixes** with a reproduction case (small test or steps to reproduce).
- **Documentation improvements** that fix something inaccurate or unclear.
- **Feature proposals** — file an issue first; we'll discuss whether the
  feature fits the project's scope before you write code.

## What to do BEFORE opening a PR

1. **Open an issue if your change is not a small bug fix.** Per Sakichi
   vision 96 (maintainers are edge developers): your time is the cost
   of unwanted features as much as it is the cost of welcome features.
   Filing an issue first protects both sides.
2. **Run the existing test suite locally.** If tests fail before your
   change, that is a separate bug — file it.
3. **Write a test for your change** if you are touching code paths that
   tests cover. If they don't, the maintainer welcomes both the change
   AND a test that newly covers it.

## What the PR description should contain

- **What changed** (one paragraph; reference the issue if filed)
- **Why** (link to the issue or explain the motivation in 2-3 sentences)
- **How tested** (names of tests run, platforms exercised)
- **Linked issue** (if applicable: `Fixes #N`, `Closes #N`)
- **Anything the reviewer should know** (breaking changes, follow-up work,
  deliberate choices that look surprising)

## What the maintainer commits to

1. **Acknowledge within ~7 days** — even a "I see this; I will look at it
   in week N" reply is more useful than silence.
2. **State the bar clearly** — if your PR doesn't meet what the project
   needs, the maintainer says specifically what's missing, not just
   "needs more work."
3. **Respect your time** — the maintainer will not ask for changes the
   project doesn't actually need. Scope creep on review is a Sakichi
   anti-pattern.
4. **Honor your "no"** — if you decide a requested change is more than
   you want to do, the maintainer can either accept what you've done,
   refactor it themselves, or close the PR with thanks. None of these
   is a punishment.
5. **Cheap rollback** — if a merge turns out to have been wrong, the
   maintainer reverts cleanly without litigating the contributor.

## Code of conduct

Be kind. Disagreement on technical decisions is welcome; disagreement on
human dignity is not. The maintainer is the final arbiter on the project's
scope; the contributor is the final arbiter on whether they want to
participate.

## Generated by SPA AI

This file was proposed by [SPA AI](https://github.com/aki1770-del/spa-ai) —
a developer agent that installs Jidoka halts as PRs. The 5 commitments above
are adapted from SPA AI's `promises.md`. Edit freely; the wording is a
starting point, not a contract you must adopt verbatim. The point is that
*some* version of these norms exists in writing, available to every new
contributor before their first PR.

If this loom is wrong for your project, delete this file. Per
[promises.md](https://github.com/aki1770-del/spa-ai/blob/main/docs/promises.md)
Promise 5: removal is a single command. Stopping must be cheap.
"""


_PR_BODY_TEMPLATE = """\
## What this PR adds

A `CONTRIBUTING.md` at the repo root with maintainer-norm-discoverable
structure:

- What contributions are welcome
- What to do BEFORE opening a PR
- What the PR description should contain
- What the maintainer commits to (5 points adapted from SPA AI's
  `promises.md`)
- Code of conduct (brief — disagreement-on-technical-decisions vs
  disagreement-on-human-dignity)

## Why this halt

Without a CONTRIBUTING.md, every new contributor must discover your norms
by trial-and-error — through PR review back-and-forth, through closed PRs
that violated unstated conventions, through chat questions you answer
individually each time. You absorb the onboarding cost
contributor-by-contributor.

With it, the file is the loom: one-time write of your norms, available to
every contributor before their first PR. Your time goes to judgment work,
not to repeated per-contributor onboarding answers.

## Sakichi vision

Vision 96 from the SPA AI doctrinal source: *Maintainers are edge developers
too — not a privileged class above contributors.* A maintainer's time is
the cost We respect. The CONTRIBUTING.md halt costs you 5 minutes of
review (this PR) to save you N×30 minutes of per-contributor onboarding
across the next year of contributions.

## What you do as the maintainer

1. Read the proposed `CONTRIBUTING.md`.
2. Edit anything that does not match how you actually run the project. The
   wording is a starting point, not a contract; the 5 commitments are
   adapted from SPA AI's `promises.md` and may not all fit your project
   shape.
3. Merge.

## Rollback

If this halt is wrong for your project, delete `CONTRIBUTING.md`. No state
is left behind. Per SPA AI's `promises.md` Promise 5: removal is a single
command — stopping must be cheap.

## Provenance

This PR was drafted by SPA AI's `ContributingMdLoom` and reviewed by a
human (the PR submitter) before opening. SPA AI proposes; the human
commits.
"""


class ContributingMdLoom:
    """Detects missing `CONTRIBUTING.md` and proposes a maintainer-dignity-shaped one."""

    loom_id = "contributing-md"
    sakichi_vision_id = 96
    method_vision_ids = [77, 18, 99]
    stance_vision_ids = [22, 25, 32, 96, 100]
    # Maintainer absorbs less per-contributor onboarding cost; first-contributor
    # discovers norms before their first PR.
    weaver_classes_served = ["maintainer", "first-contributor"]

    # Standard locations CONTRIBUTING.md is recognized at by GitHub.
    # If the file exists at any of these, the loom does not propose.
    _CHECKED_PATHS = (
        Path("CONTRIBUTING.md"),
        Path(".github/CONTRIBUTING.md"),
        Path("docs/CONTRIBUTING.md"),
    )

    def detect(self, repo_root: Path) -> list[LoomFinding]:
        """Return a single finding if no CONTRIBUTING.md exists at any standard path.

        Standard paths: `CONTRIBUTING.md`, `.github/CONTRIBUTING.md`,
        `docs/CONTRIBUTING.md` — the three locations GitHub recognizes.
        """
        for rel in self._CHECKED_PATHS:
            if (repo_root / rel).exists():
                return []
        return [
            LoomFinding(
                loom_id=self.loom_id,
                target_path=Path("CONTRIBUTING.md"),
                reason=(
                    "No `CONTRIBUTING.md` (or `.github/CONTRIBUTING.md`, "
                    "or `docs/CONTRIBUTING.md`) at repo root. New "
                    "contributors must discover maintainer norms by "
                    "trial-and-error; the maintainer absorbs the "
                    "onboarding cost contributor-by-contributor."
                ),
                sakichi_vision_id=self.sakichi_vision_id,
                severity="medium",
            )
        ]

    def propose_patch(self, finding: LoomFinding, repo_root: Path) -> LoomPatch:
        """Return a patch with the default CONTRIBUTING.md + V96-anchored PR body.

        `repo_root` unused — this loom always creates a new file."""
        return LoomPatch(
            loom_id=self.loom_id,
            target_path=finding.target_path,
            contents=_DEFAULT_CONTRIBUTING,
            pr_body=_PR_BODY_TEMPLATE,
        )
