"""PreCommitFormatterLoom — installs `.pre-commit-config.yaml` if absent.

Sakichi vision 20: stopping must be cheap, or operators will hesitate.
A pre-commit hook is the cheapest possible stop — it fires on every
commit, costs sub-second runtime, never lets formatting drift reach
PR review. Without this halt, maintainers absorb the drift during
review or after merge in CI; either is the wrong line of defense.
"""
from __future__ import annotations

from pathlib import Path

from .base import LoomFinding, LoomPatch

_DEFAULT_CONFIG = """\
# Generated by SPA AI's PreCommitFormatterLoom.
#
# Why this halt: pre-commit catches formatting drift at source, so
# maintainers do not absorb it during PR review.
# Sakichi vision: 20 (stopping must be cheap).
#
# Run `pre-commit install` once locally to enable on this clone.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
"""

_PR_BODY_TEMPLATE = """\
## What this PR adds

A `.pre-commit-config.yaml` at the repo root with five base hooks:

- `trailing-whitespace`
- `end-of-file-fixer`
- `check-yaml`
- `check-merge-conflict`
- `check-added-large-files`

## Why this halt

This PR installs a Jidoka halt at commit time. Without it, formatting
drift (trailing whitespace, missing end-of-file newline, malformed
YAML) is caught by reviewers — sometimes at PR review time, sometimes
after merge by CI, sometimes never. Each of those paths consumes
maintainer attention that should have been spent on judgment work.

With this halt, the catch happens at `git commit`, before the change
can land in a PR. The maintainer never sees it.

## Sakichi vision

Vision 20 from the SPA AI doctrinal source: *Stopping must be cheap,
or operators will hesitate; design the halt to cost less than the
defect.* A `pre-commit` hook is the cheapest possible stop — it fires
on every commit, costs sub-second runtime, and never lets the defect
reach the reviewer.

## What you do as the maintainer

1. Review this `.pre-commit-config.yaml`.
2. Run `pre-commit install` once locally to enable the hook on your
   clone (and add the same step to your `CONTRIBUTING.md` so new
   contributors do the same).
3. Merge this PR.

## Rollback

If this halt is wrong for your project, delete
`.pre-commit-config.yaml` and run `pre-commit uninstall`. No state
is left behind. Per promises.md Promise 5, removal is a single
command — stopping must be cheap.

## Provenance

This PR was drafted by SPA AI's `PreCommitFormatterLoom` and reviewed
by a human (the PR submitter) before opening. SPA AI proposes; the
human commits.
"""


class PreCommitFormatterLoom:
    """Detects missing `.pre-commit-config.yaml` and proposes one."""

    loom_id = "pre-commit-formatter"
    sakichi_vision_id = 20
    method_vision_ids = [77, 18, 99]
    stance_vision_ids = [22, 25, 32, 100]

    def detect(self, repo_root: Path) -> list[LoomFinding]:
        """Return a single finding if no pre-commit config exists.

        Both `.pre-commit-config.yaml` and `.pre-commit-config.yml`
        are accepted as evidence the loom is already present.
        """
        for name in (".pre-commit-config.yaml", ".pre-commit-config.yml"):
            if (repo_root / name).exists():
                return []
        return [
            LoomFinding(
                loom_id=self.loom_id,
                target_path=Path(".pre-commit-config.yaml"),
                reason=(
                    "No `.pre-commit-config.yaml` (or `.yml`) at repo root. "
                    "Formatting drift currently has no commit-time halt."
                ),
                sakichi_vision_id=self.sakichi_vision_id,
                severity="medium",
            )
        ]

    def propose_patch(self, finding: LoomFinding) -> LoomPatch:
        """Return a patch with default config + Jidoka-rationale PR body."""
        return LoomPatch(
            loom_id=self.loom_id,
            target_path=finding.target_path,
            contents=_DEFAULT_CONFIG,
            pr_body=_PR_BODY_TEMPLATE,
        )
