"""PreCommitFormatterRustLoom — Rust-aware pre-commit config installer.

Specialization of PreCommitFormatterLoom for Rust projects (any repo
with `Cargo.toml` at the root). Detection fires only when:

  1. `Cargo.toml` is present at the repo root (Rust crate or workspace).
  2. No pre-commit config file exists yet.

The proposed config is the language-agnostic five-hook baseline plus a
local `rustfmt` hook. `clippy` is intentionally *not* in the pre-commit
config — clippy recompiles and is too slow for a commit-time halt
(violates V20 "stopping must be cheap, or operators will hesitate").
clippy belongs in CI; the proposal's PR body says so.

Sakichi vision 20: stopping must be cheap. The right line of defense
for formatting is at commit time; the right line of defense for slow
checks is in CI. This loom places each at its correct station.
"""
from __future__ import annotations

from pathlib import Path

from .base import LoomFinding, LoomPatch

_RUST_CONFIG = """\
# Generated by SPA AI's PreCommitFormatterRustLoom.
#
# Why this halt: pre-commit catches formatting drift at source, so
# maintainers do not absorb it during PR review. The rustfmt hook
# below runs `cargo fmt -- --check` on the workspace; it halts the
# commit if any Rust file needs formatting and does NOT mutate files.
# The `types: [rust]` filter means commits not touching any `.rs` file
# skip the hook entirely (no toolchain cost on docs-only commits).
#
# clippy is deliberately NOT in this pre-commit config — clippy
# recompiles and would violate Sakichi vision 20 ("stopping must be
# cheap, or operators will hesitate"). Run clippy in CI, not at
# commit time. A reasonable CI step:
#   - cargo clippy --all-targets --all-features -- -D warnings
#
# Run `pre-commit install` once locally to enable on this clone.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt (cargo fmt -- --check)
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false
"""

_PR_BODY_TEMPLATE = """\
## What this PR adds

A `.pre-commit-config.yaml` at the repo root tuned for Rust projects:

- Five language-agnostic hooks: `trailing-whitespace`, `end-of-file-fixer`,
  `check-yaml`, `check-merge-conflict`, `check-added-large-files`.
- One Rust-specific hook: `rustfmt` as a local hook running
  `cargo fmt -- --check`. The `--check` flag means the hook halts on
  formatting drift; it does NOT mutate your files. Respects your
  `rustfmt.toml` if one exists.

## Why this halt

This PR installs a Jidoka halt at commit time. Without it, formatting
drift (whitespace, malformed YAML, unformatted Rust) is caught by
reviewers — sometimes at PR review time, sometimes after merge by CI,
sometimes never. Each path consumes maintainer attention that should
have been spent on judgment work.

With this halt, the catch happens at `git commit`, before the change
can land in a PR. The maintainer never sees it.

## Why clippy is *not* in this pre-commit config

`clippy` recompiles your crate on each run, which can take many
seconds. A pre-commit hook that takes more than ~1s creates pressure
on the contributor to skip it, which silently disables the halt. Per
Sakichi vision 20: *stopping must be cheap, or operators will
hesitate*. clippy belongs in CI, not at commit time. A reasonable CI
step:

```yaml
- run: cargo clippy --all-targets --all-features -- -D warnings
```

## Sakichi vision

Vision 20 from the SPA AI doctrinal source: *Stopping must be cheap,
or operators will hesitate; design the halt to cost less than the
defect.* `cargo fmt -- --check` is sub-second on most workspaces and
is skipped entirely by pre-commit's `types: [rust]` filter when no
`.rs` files are staged in the commit. `clippy` would recompile and
take many seconds — wrong station. This config places each check at
the station where it costs least.

## What you do as the maintainer

1. Review this `.pre-commit-config.yaml`.
2. Run `pre-commit install` once locally to enable the hook on your
   clone (and add the same step to your `CONTRIBUTING.md` so new
   contributors do the same).
3. If you do not already have a clippy CI step, consider adding one
   (out of scope for this PR — that's a separate loom).
4. Merge this PR.

## Rollback

If this halt is wrong for your project, delete
`.pre-commit-config.yaml` and run `pre-commit uninstall`. No state
is left behind. Per promises.md Promise 5, removal is a single
command — stopping must be cheap.

## Provenance

This PR was drafted by SPA AI's `PreCommitFormatterRustLoom` and
reviewed by a human (the PR submitter) before opening. SPA AI
proposes; the human commits.
"""


class PreCommitFormatterRustLoom:
    """Detects missing pre-commit config in Rust projects; proposes one.

    Detection signal: `Cargo.toml` at repo root (Rust crate or
    workspace) AND no `.pre-commit-config.{yaml,yml}` at repo root.

    Specialization of PreCommitFormatterLoom — both can coexist in
    the registry; on a Rust repo the Rust loom fires and the generic
    loom also fires (they have the same target_path). The CLI's
    --apply path refuses to overwrite existing files, so whichever
    is proposed first wins; humans choose at propose time which
    loom_id to invoke.
    """

    loom_id = "pre-commit-formatter-rust"
    sakichi_vision_id = 20
    method_vision_ids = [77, 18, 99]
    stance_vision_ids = [22, 25, 32, 100]
    # Same chain as PreCommitFormatterLoom, Rust-specialized.
    weaver_classes_served = ["maintainer", "first-contributor"]

    def detect(self, repo_root: Path) -> list[LoomFinding]:
        if not (repo_root / "Cargo.toml").exists():
            return []
        for name in (".pre-commit-config.yaml", ".pre-commit-config.yml"):
            if (repo_root / name).exists():
                return []
        return [
            LoomFinding(
                loom_id=self.loom_id,
                target_path=Path(".pre-commit-config.yaml"),
                reason=(
                    "Rust project (Cargo.toml present) with no "
                    "`.pre-commit-config.yaml`. Formatting and rustfmt "
                    "drift currently has no commit-time halt."
                ),
                sakichi_vision_id=self.sakichi_vision_id,
                severity="medium",
            )
        ]

    def propose_patch(self, finding: LoomFinding, repo_root: Path) -> LoomPatch:
        """`repo_root` unused — this loom always creates a new file."""
        return LoomPatch(
            loom_id=self.loom_id,
            target_path=finding.target_path,
            contents=_RUST_CONFIG,
            pr_body=_PR_BODY_TEMPLATE,
        )
